// Randomized stress tests for gpurhh::HashTable.
//
// Two families of tests:
//
// 1. Uniform-key stress (test_small_*, test_gigabyte_*):
//    Inserts N distinct keys generated by a bit-mixing permutation
//    (essentially a deterministic high-entropy substitute for an RNG).
//    Distinctness by construction means we don't need host-side dedup,
//    which is what lets the gigabyte tests fit in memory.
//
// 2. Random duplicates with sum reduction (test_sum_*):
//    Inserts N (key, value) pairs drawn from std::mt19937 with deliberate
//    duplicate keys, using a HashTable parameterized with sum_op as the
//    Reduction. Since `+` is associative and commutative, the final value
//    in each slot is deterministic regardless of CAS interleaving order:
//    it must equal the host-computed sum of all values for that key.

#include "isolated.cuh"

#include <cstdio>
#include <random>
#include <unordered_map>

namespace {

// --- (1) Uniform-key stress -----------------------------------------------

// Host-side bit-mixing (MurmurHash3 fmix32). Bijective on uint32_t.
inline std::uint32_t mix_key(std::uint32_t x) noexcept {
    x ^= x >> 16;
    x *= 0x85ebca6bu;
    x ^= x >> 13;
    x *= 0xc2b2ae35u;
    x ^= x >> 16;
    return x;
}

inline std::uint32_t derive_value(std::uint32_t k) noexcept {
    return k * 31u + 17u;
}

void verify_uniform_state(const std::vector<TestTable::Slot>& state,
                          std::size_t expected_count) {
    std::size_t occupied = 0;
    for (const auto& slot : state) {
        if (slot.key != TestTable::empty_key) {
            assert(slot.value == derive_value(slot.key));
            ++occupied;
        }
    }
    assert(occupied == expected_count);
}

void run_uniform(std::size_t capacity, double load_factor, std::uint32_t seed) {
    const std::size_t N = static_cast<std::size_t>(capacity * load_factor);
    const double table_gb =
        static_cast<double>(capacity * sizeof(TestTable::Slot)) /
        static_cast<double>(std::size_t{1} << 30);
    std::printf("  uniform: capacity=%zu slots (%.3f GB table), load_factor=%.2f, N=%zu\n",
                capacity, table_gb, load_factor, N);
    std::fflush(stdout);

    TestTable table(capacity);

    std::vector<std::uint32_t> keys, values;
    keys.reserve(N);
    values.reserve(N);
    std::uint32_t i = 0;
    while (keys.size() < N) {
        const auto k = mix_key(i + seed);
        if (k != TestTable::empty_key) {
            keys.push_back(k);
            values.push_back(derive_value(k));
        }
        ++i;
    }

    run_insert(table, keys, values);
    const auto state = read_state(table);
    verify_uniform_state(state, N);
    assert_robin_hood_invariant(table, state);

    std::size_t free_bytes = 0, total_bytes = 0;
    cudaMemGetInfo(&free_bytes, &total_bytes) >> CUDA_CHECK;
    const double used_gb = (total_bytes - free_bytes) /
        static_cast<double>(std::size_t{1} << 30);
    std::printf("    device memory in use after test: %.3f GB\n", used_gb);
}

constexpr std::size_t kSmallCapacity = 4096;

void test_small_load_factor_0_5()  { run_uniform(kSmallCapacity, 0.5,  0xC0FFEEu); }
void test_small_load_factor_0_7()  { run_uniform(kSmallCapacity, 0.7,  0xDEADBEEFu); }
void test_small_load_factor_0_85() { run_uniform(kSmallCapacity, 0.85, 0xCAFEBABEu); }

// 2^27 slots × 8 bytes = 1 GiB table. ~1.5 GB host + ~1.5 GB device peak.
constexpr std::size_t kGigabyteCapacity = std::size_t{1} << 27;

void test_gigabyte_load_factor_0_5() { run_uniform(kGigabyteCapacity, 0.5, 0xFEEDFACEu); }
void test_gigabyte_load_factor_0_7() { run_uniform(kGigabyteCapacity, 0.7, 0xBADC0DEDu); }

// --- (2) Random duplicates with sum reduction ----------------------------

using SumTable = gpurhh::HashTable<
    std::uint32_t, std::uint32_t,
    IdentityHash,
    gpurhh::default_empty_key<std::uint32_t>::key,
    gpurhh::sum_op>;

void run_sum_reduction(std::size_t capacity,
                       std::size_t n_inserts,
                       std::uint32_t key_range,
                       std::uint32_t seed) {
    std::printf("  sum: capacity=%zu, N=%zu inserts, key_range=[0,%u), seed=0x%X\n",
                capacity, n_inserts, key_range, seed);
    std::fflush(stdout);

    SumTable table(capacity);

    // Generate (key, value) pairs and accumulate the expected sums per key.
    std::mt19937 rng(seed);
    std::uniform_int_distribution<std::uint32_t> key_dist(0, key_range - 1);
    std::uniform_int_distribution<std::uint32_t> value_dist(0, 0xFFFFu);

    std::vector<std::uint32_t> keys(n_inserts), values(n_inserts);
    std::unordered_map<std::uint32_t, std::uint32_t> expected_sums;
    expected_sums.reserve(key_range);
    for (std::size_t i = 0; i < n_inserts; ++i) {
        const auto k = key_dist(rng);
        const auto v = value_dist(rng);
        keys[i]   = k;
        values[i] = v;
        // uint32_t addition wraps mod 2^32 — same semantics as device sum_op.
        expected_sums[k] += v;
    }

    run_insert(table, keys, values);
    const auto state = read_state(table);

    // Every occupied slot's value must equal the host-computed sum for
    // that key; every unique key must appear exactly once in the table.
    std::size_t occupied = 0;
    for (const auto& slot : state) {
        if (slot.key != SumTable::empty_key) {
            const auto it = expected_sums.find(slot.key);
            assert(it != expected_sums.end());
            assert(slot.value == it->second);
            ++occupied;
        }
    }
    assert(occupied == expected_sums.size());

    assert_robin_hood_invariant(table, state);
}

// 4096-slot table, 10000 inserts over key_range 1000 → ~10 dups per key,
// ~1000 unique keys, load factor ≈ 0.24. Tests the reduction path under
// heavy contention (each unique key receives several concurrent inserts).
void test_sum_small() {
    run_sum_reduction(/*capacity=*/4096, /*n_inserts=*/10'000,
                      /*key_range=*/1'000, /*seed=*/0xABCDEFu);
}

// 65536-slot table, 1M inserts over key_range 50k → ~20 dups per key,
// ~50k unique keys, load factor ≈ 0.76. Larger-scale stress.
void test_sum_large() {
    run_sum_reduction(/*capacity=*/65'536, /*n_inserts=*/1'000'000,
                      /*key_range=*/50'000, /*seed=*/0x12345678u);
}

} // namespace

int main() {
    test_small_load_factor_0_5();
    test_small_load_factor_0_7();
    test_small_load_factor_0_85();
    test_gigabyte_load_factor_0_5();
    test_gigabyte_load_factor_0_7();
    test_sum_small();
    test_sum_large();
    std::printf("test_randomized: all tests passed.\n");
    return 0;
}
